from lib import *
##
#Begin Program
print('')
pyautogui.PAUSE = 1
pyautogui.locateCenterOnScreen(r'C:')
print('')
#
pyautogui.PAUSE = 3
pyautogui.doubleClick(255,138)
pyautogui.click(1053, 135)
press('enter', 1)
press('esc', 1)
pyautogui.PAUSE = 2
type_('2')
press('enter', 1)
# Enter JBA reports
print('')
changeco('')
changerpt('')
pyautogui.typewrite('')
pyautogui.click(502,274)
pyautogui.typewrite('')
press(' ', 2)
type_(today)
press(' ', 2)
pyautogui.click(440, 600)
type_('')
press('enter', 1)
press('f8', 1)
print('')
changerpt('')
type_('')
pyautogui.click(438, 365)
type_('')
pyautogui.click(790, 361)
type_('')
pyautogui.click(438, 422)
type_('')
press('enter', 1)
('f8', 1)
#
print('')
changerpt('')
type_('')
pyautogui.click(660, 654)
type_('')
press('enter', 1)
type_('')
press('enter', 1)
type_('N')
press('enter', 1)
press('f8', 1)
press('down',5)
type_('1')
type_('1')
press('pgdn', 1)
press('down', 1)
type_('1')
press('f8', 1)
#
print('')
changerpt('')
type_('')
pyautogui.click(566, 422)
type_('')
press(' ', 3)
type_('Y')
pyautogui.press('enter')
type_('Y')
pyautogui.PAUSE = 1
pyautogui.hotkey('F8')
print('')
changeco(' ')
changerpt(' ')
type_('')
pyautogui.click(566, 422)
pyautogui.typewrite('*')
press('down', 3)
type_('Y')
pyautogui.press('enter')
type_('Y')
pyautogui.PAUSE = 1
pyautogui.hotkey('F8')
#
print('')
changeco('')
changerpt('')
pyautogui.typewrite('')
pyautogui.click(566, 422)
pyautogui.typewrite('')
press(' ', 3)
type_('Y')
pyautogui.press('enter')
type_('Y')
pyautogui.PAUSE = 1
pyautogui.hotkey('F8')
print('Done!')


